[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "titoleng09", email = "toruleng@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
